{% set name = "rdp" %}
{% set version = "0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rdp-{{ version }}.tar.gz
  sha256: 19ec92f0803587891a00b439441e5e23fc9410500983f02941e4cf9ac3113e4b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - rdp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/fhirschmann/rdp
  summary: Pure Python implementation of the Ramer-Douglas-Peucker algorithm
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gonzalocasas
